services:
  - type: web
    name: privacyguard-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: API_SECRET_KEY
        value: Wb36XsqhYwRsxcXU
      - key: MODEL_NAME
        value: gemini-1.5-flash

  - type: web
    name: privacyguard-frontend
    env: php
    rootDir: frontend
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: PYTHON_API_URL
        value: https://privacyguard-backend.onrender.com/api/v1/audit/url
      - key: API_SECRET_KEY
        value: Wb36XsqhYwRsxcXU
      - key: INERTIA_SSR_ENABLED
        value: false
